# Site Settings
name: Jack Reed
title: Jack Reed | Scrum Master
description: Jackflix is a template for Jekyll inspired by Netflix.

tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify

show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Posts
    url: /posts/
  - title: People & Teams
    url: /People&Teams
  - title: Product
    url: /Product
  - title: Organisation & Change
    url: /Organisation&Change

# Social Media Settings
instagram_username: instagram_username
linkedin_username: linkedin_username

# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true

# Advanced Settings
baseurl: "/reed" # the subpath of your site (starts with a slash, no trailing slash)
url: "https://iamjackreed.github.io" # the main domain
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false
future: true

# SASS
sass:
  style: compressed

# Plugins (GitHub Pages supported)
plugins:
  - jekyll-paginate

# Exclude my node related stuff
exclude: [
  'docs/',
  'vendor/',
  'LICENSE',
  'CHANGELOG.md',
  'Jackflix.gemspec',
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]
